In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

/Users/rohitramaswamy/Desktop/programming-stuff/sports-data-scraping/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:


headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

In [4]:
# Define the function to separate name and code
def separate_name_and_code(input_string):
    name, code = input_string.split(' (')
    code = code.rstrip(')')
    return pd.Series([name, code])


def clean_countries(text):
    text = text.replace('ICC', '')
    text = text.replace('Afr', '')
    text = text.replace('/', '')
    text = text.replace('Asia', '')

    return text
# Initialize current_df correctly
current_df = pd.DataFrame(columns=["Player"])

year = 1980
for i in range(2025-year):
    url = f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;spanmax1=15+Jul+{year};spanval1=span;team=7;template=results;type=batting'
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Check if the request was successful

        # Parse the HTML content
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find all tables in the page
        tables = soup.find_all('table')

        # Convert the first table to a pandas DataFrame
        if tables:
            df = pd.DataFrame(pd.read_html(StringIO(str(tables[2])))[0]).head(20)
            if 'Player' in df.columns and 'Runs' in df.columns:
                df = df[['Player', 'Runs']]
                df.rename(columns={'Runs': f'{year}'}, inplace=True)
                # df[['Player', 'Country']] = df['Player'].apply(separate_name_and_code)

                current_df = pd.merge(current_df, df, on='Player', how='outer')
                # current_df['Country'] = current_df['Country_y'].combine_first(current_df['Country_x'])
                # current_df = current_df.drop(columns=['Country_x', 'Country_y'])




            else:
                print(f"'Player' or 'Runs' column not found for the year {year}")
        else:
            print("No tables found on the page.")
    except requests.HTTPError as e:
        print(f"HTTP error occurred: {e.response.status_code} - {e.response.reason}")
    except Exception as e:
        print(f"An error occurred: {str(e)}")

    year = year + 1
    





# Apply the function and create two new columns


# current_df['Country'] = current_df['Country'].apply(clean_countries)
# Apply the function to the column


print(current_df)

              Player    1980    1981    1982    1983    1984    1985    1986  \
0          AH Kardar   847.0   847.0   847.0   847.0     NaN     NaN     NaN
1       Aamer Sohail     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2          Alimuddin  1091.0  1091.0  1091.0  1091.0  1091.0  1091.0  1091.0
3        Asad Shafiq     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4         Asif Iqbal  3575.0  3575.0  3575.0  3575.0  3575.0  3575.0  3575.0
5          Azhar Ali     NaN     NaN     NaN     NaN     NaN     NaN     NaN
6         Babar Azam     NaN     NaN     NaN     NaN     NaN     NaN     NaN
7     Hanif Mohammad  3915.0  3915.0  3915.0  3915.0  3915.0  3915.0  3915.0
8     Haroon Rasheed   890.0   890.0  1068.0  1217.0  1217.0  1217.0  1217.0
9         Ijaz Ahmed     NaN     NaN     NaN     NaN     NaN     NaN     NaN
10        Imran Khan   979.0  1183.0  1330.0  1853.0  2023.0  2023.0  2140.0
11      Imtiaz Ahmed  2079.0  2079.0  2079.0  2079.0  2079.0  2079.0  2079.0
12     Intikhab Alam  1493.0  1493.0  1493.0  1493.0  1493.0  1493.0  1493.0
13    Inzamam-ul-Haq     NaN     NaN     NaN     NaN     NaN     NaN     NaN
14       Javed Burki  1341.0  1341.0  1341.0  1341.0  1341.0  1341.0  1341.0
15     Javed Miandad  2433.0  2663.0  3044.0  3992.0  4519.0  5044.0  5413.0
16        Majid Khan  3562.0  3716.0  3900.0  3931.0  3931.0  3931.0  3931.0
17     Misbah-ul-Haq     NaN     NaN     NaN     NaN     NaN     NaN     NaN
18   Mohammad Hafeez     NaN     NaN     NaN     NaN     NaN     NaN     NaN
19   Mohammad Yousuf     NaN     NaN     NaN     NaN     NaN     NaN     NaN
20       Mohsin Khan     NaN     NaN     NaN  1516.0  2165.0  2468.0  2661.0
21         Moin Khan     NaN     NaN     NaN     NaN     NaN     NaN     NaN
22    Mudassar Nazar   888.0   888.0  1094.0  2138.0  2542.0  3099.0  3445.0
23  Mushtaq Mohammad  3643.0  3643.0  3643.0  3643.0  3643.0  3643.0  3643.0
24        Qasim Umar     NaN     NaN     NaN     NaN     NaN  1128.0  1431.0
25        Ramiz Raja     NaN     NaN     NaN     NaN     NaN     NaN     NaN
26    Sadiq Mohammad  2493.0  2579.0  2579.0  2579.0  2579.0  2579.0  2579.0
27       Saeed Ahmed  2991.0  2991.0  2991.0  2991.0  2991.0  2991.0  2991.0
28       Saeed Anwar     NaN     NaN     NaN     NaN     NaN     NaN     NaN
29      Saleem Malik     NaN     NaN     NaN     NaN     NaN  1242.0  1423.0
30    Sarfaraz Ahmed     NaN     NaN     NaN     NaN     NaN     NaN     NaN
31     Sarfraz Nawaz     NaN     NaN     NaN     NaN  1045.0     NaN     NaN
32   Shoaib Mohammad     NaN     NaN     NaN     NaN     NaN     NaN     NaN
33      Taufeeq Umar     NaN     NaN     NaN     NaN     NaN     NaN     NaN
34       Waqar Hasan  1071.0  1071.0  1071.0  1071.0  1071.0     NaN     NaN
35       Wasim Akram     NaN     NaN     NaN     NaN     NaN     NaN     NaN
36        Wasim Bari  1035.0  1069.0  1109.0  1259.0  1366.0  1366.0  1366.0
37        Wasim Raja  1776.0  2022.0  2269.0  2321.0  2678.0  2821.0  2821.0
38    Wazir Mohammad   801.0   801.0   801.0     NaN     NaN     NaN     NaN
39       Younis Khan     NaN     NaN     NaN     NaN     NaN     NaN     NaN
40      Zaheer Abbas  2662.0  2719.0  3023.0  4073.0  4747.0  5058.0  5062.0

      1987    1988  ...    2015    2016     2017     2018     2019     2020  \
0      NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
1      NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
2   1091.0  1091.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
3      NaN     NaN  ...     NaN     NaN   3431.0   3768.0   4323.0   4593.0
4   3575.0  3575.0  ...  3575.0  3575.0   3575.0   3575.0   3575.0   3575.0
5      NaN     NaN  ...  3393.0  3457.0   4968.0   5202.0   5669.0   5919.0
6      NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
7   3915.0  3915.0  ...  3915.0  3915.0   3915.0   3915.0   3915.0   3915.0
8   1217.0  1217.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
9      NaN     NaN  ...  3315.0  3315.0   3315.0   3315.0   3315.0   3315.0
10  2615.0  2860.0  ...  3807.0  3807.0   3807.0   3807.0   3807.0   3807.0
11  2079.0  2079.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
12  1493.0  1493.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
13     NaN     NaN  ...  8829.0  8829.0   8829.0   8829.0   8829.0   8829.0
14  1341.0  1341.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
15  5912.0  6621.0  ...  8832.0  8832.0   8832.0   8832.0   8832.0   8832.0
16  3931.0  3931.0  ...  3931.0  3931.0   3931.0   3931.0   3931.0   3931.0
17     NaN     NaN  ...  4000.0  4466.0   5222.0   5222.0   5222.0   5222.0
18     NaN     NaN  ...  2970.0  3390.0   3452.0   3452.0   3652.0   3652.0
19     NaN     NaN  ...  7530.0  7530.0   7530.0   7530.0   7530.0   7530.0
20  2709.0  2709.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
21     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
22  3538.0  3991.0  ...  4114.0  4114.0   4114.0   4114.0   4114.0   4114.0
23  3643.0  3643.0  ...  3643.0  3643.0   3643.0   3643.0   3643.0   3643.0
24  1502.0  1502.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
25     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
26  2579.0  2579.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
27  2991.0  2991.0  ...  2991.0  2991.0   2991.0   2991.0   2991.0   2991.0
28     NaN     NaN  ...  4052.0  4052.0   4052.0   4052.0   4052.0   4052.0
29  1707.0  2140.0  ...  5768.0  5768.0   5768.0   5768.0   5768.0   5768.0
30     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
31     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
32     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
33     NaN     NaN  ...  2963.0  2963.0   2963.0   2963.0   2963.0   2963.0
34     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
35     NaN     NaN  ...  2898.0  2898.0      NaN      NaN      NaN      NaN
36  1366.0  1366.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
37  2821.0  2821.0  ...     NaN     NaN      NaN      NaN      NaN      NaN
38     NaN     NaN  ...     NaN     NaN      NaN      NaN      NaN      NaN
39     NaN     NaN  ...  8814.0  9174.0  10099.0  10099.0  10099.0  10099.0
40  5062.0  5062.0  ...  5062.0  5062.0   5062.0   5062.0   5062.0   5062.0

       2021     2022     2023     2024
0       NaN      NaN      NaN      NaN
1       NaN      NaN      NaN      NaN
2       NaN      NaN      NaN      NaN
3    4660.0   4660.0   4660.0   4660.0
4    3575.0   3575.0   3575.0   3575.0
5    6579.0   7021.0   7142.0   7142.0
6       NaN      NaN   3696.0   3898.0
7    3915.0   3915.0   3915.0   3915.0
8       NaN      NaN      NaN      NaN
9    3315.0   3315.0   3315.0   3315.0
10   3807.0   3807.0   3807.0   3807.0
11      NaN      NaN      NaN      NaN
12      NaN      NaN      NaN      NaN
13   8829.0   8829.0   8829.0   8829.0
14      NaN      NaN      NaN      NaN
15   8832.0   8832.0   8832.0   8832.0
16   3931.0   3931.0   3931.0   3931.0
17   5222.0   5222.0   5222.0   5222.0
18   3652.0   3652.0   3652.0   3652.0
19   7530.0   7530.0   7530.0   7530.0
20      NaN      NaN      NaN      NaN
21      NaN      NaN      NaN      NaN
22   4114.0   4114.0   4114.0   4114.0
23   3643.0   3643.0   3643.0   3643.0
24      NaN      NaN      NaN      NaN
25      NaN      NaN      NaN      NaN
26      NaN      NaN      NaN      NaN
27   2991.0   2991.0      NaN      NaN
28   4052.0   4052.0   4052.0   4052.0
29   5768.0   5768.0   5768.0   5768.0
30      NaN      NaN   2992.0   3031.0
31      NaN      NaN      NaN      NaN
32      NaN      NaN      NaN      NaN
33   2963.0   2963.0      NaN      NaN
34      NaN      NaN      NaN      NaN
35      NaN      NaN      NaN      NaN
36      NaN      NaN      NaN      NaN
37      NaN      NaN      NaN      NaN
38      NaN      NaN      NaN      NaN
39  10099.0  10099.0  10099.0  10099.0
40   5062.0   5062.0   5062.0   5062.0

[41 rows x 46 columns]

In [36]:

current_df['Country'] = current_df['Country'].apply(clean_countries)
# Apply the function to the column

current_df.replace(to_replace=r'\+', value='', regex=True, inplace=True)

In [37]:

# List of countries
countries = pd.read_csv(r'tools/shortcodes.csv', dtype=str)  

print(countries.tail(5))

# row_index = countries[countries["Code"] == 'IND'].index[0]
# print(row_index)

# Function to get Shortcode based on Code
def get_row(input):
    rows = countries[countries["Code"] == input].index
    if len(rows) > 0:
        row_index = rows[0]
        if len(countries.loc[row_index, "Lowercase shortcode"]) == 2:
            return f'https://public.flourish.studio/country-flags/svg/{countries.loc[row_index, "Lowercase shortcode"]}.svg'
        else:
            return countries.loc[row_index, "Lowercase shortcode"]
    else:
        return 'Unknown'  # Or any default value you want to assign

# Apply function to get Shortcode for each country in current_df
current_df["Flag"] = current_df["Country"].apply(get_row)

print(current_df.head(5))

            Name  Code Shortcode  \
245        Yemen    YE      :YE:
246       Zambia    ZM      :ZM:
247     Zimbabwe   ZIM     :ZIM:
248  West Indies    WI       NaN
249     Scotland  SCOT       NaN

                                   Lowercase shortcode
245                                                 ye
246                                                 zm
247                                                 zw
248  https://upload.wikimedia.org/wikipedia/en/9/9b...
249  https://upload.wikimedia.org/wikipedia/commons...
           Player 1980 1981 1982 1983 1984 1985 1986 1987 1988  ... 2017 2018  \
0      A Flintoff  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1        A Jadeja  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
2     A Ranatunga  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
3       A Symonds  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
4  AB de Villiers  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  194  204

  2019 2020 2021 2022 2023 2024 Country  \
0  NaN  NaN  NaN  NaN  NaN  NaN     ENG
1  NaN  NaN  NaN  NaN  NaN  NaN     IND
2  NaN  NaN  NaN  NaN  NaN  NaN      SL
3  NaN  NaN  NaN  NaN  NaN  NaN     AUS
4  204  204  204  204  204  204      SA

                                                Flag
0  https://public.flourish.studio/country-flags/s...
1  https://public.flourish.studio/country-flags/s...
2  https://public.flourish.studio/country-flags/s...
3  https://public.flourish.studio/country-flags/s...
4  https://public.flourish.studio/country-flags/s...

[5 rows x 48 columns]

In [5]:
excel_file = "output.xlsx" 
 
# Write DataFrame to Excel 
current_df.to_excel(excel_file, index=False)